### ISSUE TITLE
Possible to use plugin via qgis_process

### ISSUE THREAD

**Issue by beedawg1985** [EarthObservation/rvt-qgis#13]
Hi, 
Is it possible to use this plugin via the qgis_process command line utility? Following install via the official QGIS repository, the rvt plugin doesn't appear in the list of providers when running `qgis_process plugins`.

[This issue](https://github.com/qgis/QGIS/issues/41120) seems to indicate that changing line 21 in metadata.txt to: `hasProcessingProvider=yes` should fix this issue.

It tried making this change and re-installing the modified plug-in and now `qgis_process list` returns:

```
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/bin/../../Resources/python/qgis/utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "~/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/rvt-qgis/__init__.py", line 36, in classFactory
    return QRVT(iface)
  File "~/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/rvt-qgis/qrvt.py", line 157, in __init__
    self.toolbar = self.iface.addToolBar(u'Relief Visualization Toolbox')
AttributeError: 'NoneType' object has no attribute 'addToolBar'

error starting plugin: rvt-qgis

Available plugins
(* indicates loaded plugins which implement Processing providers)

* QuickOSM
  rvt-qgis
  shapetools
* processing 
```

**Comment by zm8597** [comment]
Hi, 

thank you for this report. I fixed the bug, the qgis_process command line utility is now working in new version (v0.7.0) 😃.

**Comment by beedawg1985** [comment]
Awesome! I'll give it a test....looking forward to crunching through my visualizations!

**Comment by zm8597** [comment]
Let me know if you find any bug or something doesn't work. 😃
