### ISSUE TITLE
Simplified local relief model crashing

### ISSUE THREAD

**Issue by Grozic-D** [EarthObservation/rvt-qgis#19]
Traceback (most recent call last):
File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rvt-qgis\processing_provider\rvt_slrm.py", line 148, in processAlgorithm
visualization_arr = rvt.vis.slrm(dem=dem_arr, radius_cell=radius, ve_factor=ve_factor, no_data=no_data)
File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rvt-qgis\rvt\vis.py", line 443, in slrm
dem_mean_filter = mean_filter(dem=dem, kernel_radius=radius_cell)
File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rvt-qgis\rvt\vis.py", line 383, in mean_filter
dem_i_nr_pixels = integral_image(dem_i_nr_pixels, np.int)
File "C:\OSGeo4W\apps\Python39\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'

**Comment by NejcCoz** [comment]
Thanks for letting us know. It seems there is a deprecation issue when using newer versions of numpy. We are working on an update which will be released in the next couple of days.

While waiting for the release please try using an older version of QGIS. For example, the function works fine on QGIS 3.22.15, which is using the numpy version 1.20.2

**Comment by NejcCoz** [comment]
The error has been fixed and we have released the update for the plugin (now version 0.9.5).

@Grozic-D Please upgrade your plugin to the latest version.

I am closing the issue, but please let us know if the error persists.

Many thanks, Nejc

**Comment by Grozic-D** [comment]
Great news,

thank you.

Dino
